trigger:
- main

pool:
  container: 'amd64/gradle:jdk8'
  name: 'Private Cloud'

steps:
- task: DownloadSecureFile@1
  name: downloadMvnSettings
  inputs:
   secureFile: 'settings.xml'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    versionSpec: '8'
    jdkArchitectureOption: 'x86'
    jdkSourceOption: 'PreInstalled'

    options: '-s $(downloadMvnSettings.secureFilePath)'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

